speedhack/api/urls.py
from django.urls import path

from .views import GetUser, GetUsers, GetUserTgLink

urlpatterns = [
    path('get_users/', GetUsers.as_view()),
    path('get_user/<str:username>/', GetUser.as_view()),
    path('get_user_tg/<str:tg_link>/', GetUserTgLink.as_view()),
]

speedhack/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    # * ссылки на страницы
    path('', views.index, name='index'),
    # ? ----------
    # * страница, для отображения ошибки 403 (может пригодится)
    # path('ratelimited/', views.ratelimited, name='ratelimited'),
    # ? ----------
    path('forum/viewed_threads/', views.viewed_threads, name='viewed_threads'),
    path('forum/my_topics/', views.my_topics, name='my_topics'),
    path('forum/favourites/', views.favourites, name='favourites'),
    path('forum/tickets/open/', views.ticket_form, name='ticket_form'),
    path('group/<slug:slug>/', views.group_free, name='group_filter_posts'),
    path('group/<slug:slug>/create_thread/', views.create_thread, name='create_thread'),
    path('members/<str:username>/', views.profile, name='profile'),
    # ? ----------
    # TODO: сделать для пользователей с привилегиями короткие ссылки на профиль
    # path('<str:username>/', views.profile, name='profile'),
    # ? ----------
    path('members/<str:username>/symps/', views.symps_view, name='symps_view'),
    path('members/<str:username>/messages/', views.messages_view, name='messages_view'),
    path('members/<str:username>/subscriptions/', views.subscriptions_view, name='subscriptions_view'),
    path('members/<str:username>/subscribers/', views.subscribers_view, name='subscribers_view'),
    path('members/<str:username>/personal-details/', views.profile_personal_info_edit, name='profile_personal_info_edit'),
    path('members/<str:username>/contact-details/', views.profile_contact_info_edit, name='profile_contact_info_edit'),
    path('members/<str:username>/upgrade/', views.upgrade_temp, name='profile_upgrade'),
    # path('members/<str:username>/safety/', views.safety, name='profile_safety'),
    path('forum/create_post/', views.post_create, name='post_create'),
    path('forum/<int:post_id>/', views.post_detail, name='post_detail'),
    path('forum/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users-bans/', views.users_bans, name='users_bans'),
    path('admin-panel/tickets/', views.tickets, name='tickets'),
    path('admin-panel/ads/', views.ads, name='ads'),
    path('tickets/<str:username>/', views.my_tickets, name='my_tickets'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('<str:username>/complaint/', views.complaint, name='complaint'),
    path('users/', views.users, name='users'),
    path('misc/banned/', views.banned, name='banned'),
    path('misc/empty-page/', views.empty_page, name='empty_page'),
    path('misc/faq/', views.faq, name='faq'),
    path('misc/faq-q/', views.faq_q, name='faq_q'),
    path('misc/rules/', views.rules, name='rules'),
    path('misc/user-ag/', views.user_ag, name='user_ag'),
    path('misc/words/', views.words, name='words'),
    path('misc/successfully/', views.successfully, name='successfully'),
    path('misc/guarantor/', views.guarantor, name='guarantor'),
    path('misc/about/', views.about_us, name='about_us'),
    path('misc/ads/', views.advertisement, name='advertisement'),
    path('payment/safe-deal/', views.safe_deal, name='safe_deal'),
    # * ссылки на действия
    path('profile/<str:username>/deposit/<int:number>/', views.deposit, name='deposit'),
    path('profile/<str:username>/ban/', views.ban, name='ban'),
    path('profile/<str:username>/upgrade/<int:number>/', views.upgrade, name='upgrade'),
    path('profile/<str:username>/comment/<str:author>/<int:comment_id>/', views.delete_profile_comment, name='delete_profile_comment'),
    path('profile/<str:username>/follow/<int:number>/', views.profile_uf, name='profile_uf'),
    path('forum/<int:post_id>/favourites-post-save/<int:number>/', views.favourites_post_save, name='favourites_post_save'),
    path('forum/<int:post_id>/close/<int:number>/', views.post_oc, name='post_oc'),
    path('forum/<int:post_id>/symps/<str:username>/', views.symps_add, name='symps_add'),
    path('forum/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('forum/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # path('forum/<int:post_id>/symps-comment/<int:comment_id>/<str:username>/', views.symps_comment_add, name='symps_comment_add'),
    path('forum/<int:post_id>/comment/edit/', views.edit_comment, name='edit_comment'),
    path('forum/<int:post_id>/del-comment/<int:id>/', views.delete_comment, name='delete_comment'),
    path('admin-panel/user-edit/<str:username>/', views.admin_user_edit, name='admin_user_edit'),
    path('admin-panel/<str:username>/ban/', views.admin_ban, name='admin_ban'),
    path('admin-panel/ticket/<int:ticket_id>/close/<int:number>/', views.ticket_oc, name='ticket_oc'),
    path('admin-panel/ticket/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),
    path('ticket/<int:ticket_id>/comment/', views.add_answer, name='add_answer'),

    # Система личных сообщений
    # path('dialogs/', views.dialogs, name='dialogs'),
    # path('dialogs/create/(?P<user_id>\d+)/', views.create_dialog, name='create_dialog'),
    # path('dialogs/(?P<chat_id>\d+)/', views.messages, name='messages'),
]

speedhack/market/urls.py
from django.urls import path

from . import views

app_name = 'market'

urlpatterns = [
    path('', views.market, name='index'),
    path('close/', views.close, name='close'),
    path('group/<slug:slug>/', views.group_free, name='group_free'),
    path('my_accs/', views.my_accs, name='my_accs'),
    path('my_buy_accs/', views.my_buy_accs, name='my_buy_accs'),
    path('<int:acc_id>/', views.acc_detail, name='acc_detail'),
    path('<int:acc_id>/buy/', views.acc_buy, name='acc_buy'),
    path('acc_sell/', views.acc_sell, name='acc_sell'),
    path('rules/', views.rules, name='rules'),
]

speedhack/speedhack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('forum.urls', namespace='forum')),
    path('api/', include('api.urls')),
    path('market/', include('market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'tools.views.error404_page'

speedhack/market/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator
from django.db import models

User = get_user_model()


class AccGroup(models.Model):
    title = models.CharField(unique=True, max_length=50, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Уникальный адрес')

    class Meta:
        verbose_name = 'Платформа'
        verbose_name_plural = 'Платформы'

    def __str__(self):
        return self.title


class Market(models.Model):
    group = models.ForeignKey(
        AccGroup,
        on_delete=models.SET_NULL,
        null=True,
        related_name='acc',
        verbose_name='Платформа',
    )
    title = models.CharField(verbose_name='Заголовок', max_length=55)
    login = models.CharField(verbose_name='Логин', max_length=50)
    password = models.CharField(verbose_name='Пароль', max_length=100)
    email = models.CharField(verbose_name='Почта', max_length=100)
    email_password = models.CharField(verbose_name='Пароль от почты', max_length=100)
    price = models.IntegerField(verbose_name='Цена', validators=[MaxValueValidator(150000)])
    description = models.TextField(verbose_name='Описание', max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    view = models.IntegerField(
        default=0,
        verbose_name='Просмотры'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Продавец',
        related_name='seller',
    )
    buyer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Покупатель',
        related_name='buyer',
    )

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.title

speedhack/market/forms.py
from django import forms

from .models import Market


class AccForm(forms.ModelForm):
    class Meta:
        model = Market
        fields = ('group', 'title', 'login', 'password', 'email', 'email_password', 'price', 'description',)

speedhack/market/views.py
import requests
from bs4 import BeautifulSoup as BS
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from users.models import CustomUser

from .forms import AccForm
from .models import AccGroup, Market


def banned_redirect(request):
    return redirect('forum:banned')


def banned(request):
    return render(request, 'users/banned.html')


def close_redirect(request):
    return redirect('market:close')


def close(request):
    return render(request, 'users/close.html')


def acc_parser():
    r = requests.get(f"https://steamcommunity.com/id/sp1edh4ck")
    html = BS(r.content, 'html.parser')
    acc_info = {
        "name": "",
        "steam_lvl": 0,
        "last_online": "",
        "two_week_hours": 0,
        "count_friend": 0,
    }
    acc_info["name"] = html.find("span", class_="actual_persona_name").text
    acc_info["steam_lvl"] = html.find("span", class_="friendPlayerLevelNum").text
    acc_info["last_online"] = html.find("div", class_="profile_in_game_header").text
    acc_info["count_friend"] = html.find_all("span", class_="profile_count_link_total")[6].text
    return acc_info


def market(request):
    if request.user.is_authenticated and request.user.rank == "заблокирован":
        return banned_redirect(request)
    accs = Market.objects.all()
    context = {
        'accs': accs,
    }
    return render(request, 'market/index.html', context)


def group_free(request, slug):
    if request.user.is_authenticated and request.user.rank == "заблокирован":
        return banned_redirect(request)
    group = get_object_or_404(AccGroup, slug=slug)
    accs = group.acc.all()
    context = {
        'accs': accs,
        'group': group,
    }
    return render(request, 'market/template_groups.html', context)


@login_required
def my_accs(request):
    if request.user.rank == "заблокирован":
        return banned_redirect(request)
    user = CustomUser.objects.get(username=request.user.username)
    accs = Market.objects.filter(author=user).all()
    context = {
        'accs': accs,
    }
    return render(request, 'market/index.html', context)


@login_required
def my_buy_accs(request):
    if request.user.rank == "заблокирован":
        return banned_redirect(request)
    user = CustomUser.objects.get(username=request.user)
    accs = Market.objects.filter(buyer=user)
    context = {
        'accs': accs,
    }
    return render(request, 'market/index.html', context)


@login_required
def acc_sell(request):
    if request.user.rank == "заблокирован":
        return banned_redirect(request)
    if request.user.rank == "пользователь":
        return close(request)
    form = AccForm(
        request.POST or None,
    )
    if request.method == 'POST':
        if form.is_valid() and request.user.is_authenticated:
            new_acc = form.save(commit=False)
            new_acc.author = request.user
            new_acc.save()
            return redirect('market:index')
    context = {
        'form': form
    }
    return render(request, 'market/acc_sell.html', context)


def acc_detail(request, acc_id):
    if request.user.is_authenticated and request.user.rank == "заблокирован":
        return banned_redirect(request)
    acc = get_object_or_404(Market, id=acc_id)
    acc.view += 1
    acc.save()
    # acc_info = acc_parser()
    context = {
        # 'acc_info': acc_info,
        'acc': acc,
    }
    return render(request, 'market/acc_detail.html', context)


@login_required
def acc_buy(request, acc_id):
    if request.user.rank == "заблокирован":
        return banned_redirect(request)
    acc = get_object_or_404(Market, id=acc_id)
    user = CustomUser.objects.get(username=request.user.username)
    if acc.buyer == None and acc.author != user and user.balance >= acc.price:
        acc.buyer = user
        user.balance -= acc.price
        user.save()
        acc.save()
    return redirect('market:acc_detail', acc_id=acc_id)


def rules(request):
    return render(request, 'market/rules.html')

speedhack/templates/market/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}speedhack / маркет{% endblock %}
{% block content %}
  <div class="main">
    <div class="frames_con" style="display: flex;">
      <div style="display: block;">
        <div class="market-sell">
          <a href="{% url 'market:acc_sell' %}" class="market-sell-button">Продать аккаунт</a>
        </div>
        <div class="market-main-left">
          <a href="https://t.me/sp1edh4ck" class="market-link-left" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-circle-question fa-lg icon-market-left"></i>Нужна помощь</a>
          <a href="{% url 'market:rules' %}" class="market-link-left" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-book fa-lg icon-market-left"></i>Правила и гарантии</a>
          <a href="{% url 'forum:group_filter_posts' 111 %}" class="market-link-left"><i class="fa-solid fa-sheet-plastic fa-lg icon-market-left"></i>Советы и гайды</a>
          <a href="" class="market-link-left"><i class="fa-solid fa-gear fa-lg icon-market-left"></i>Настройки маркета</a>
          <a href="{% url 'forum:profile_upgrade' request.user %}" class="market-link-left"><i class="fa-solid fa-angles-up fa-lg icon-market-left"></i>Повышение статуса</a>
          <hr style="margin: 5px 0px; border: 1px solid #444444;">
          <a href="{% url 'forum:post_detail' 19 %}" class="market-link-left"><i class="fa-solid fa-newspaper fa-lg icon-market-left"></i>Изменения на сайте</a>
          <a href="{% url 'forum:group_filter_posts' 108 %}" class="market-link-left"><i class="fa-solid fa-flag fa-lg icon-market-left"></i>Сообщить о баге</a>
          <a href="{% url 'forum:group_filter_posts' 109 %}" class="market-link-left"><i class="fa-solid fa-circle-info fa-lg icon-market-left"></i>Предложить идею</a>
          <a href="" class="market-link-left"><i class="fa-solid fa-code fa-lg icon-market-left"></i>API для разработчика</a>
          <hr style="margin: 5px 0px; border: 1px solid #444444;">
          <a href="" class="market-link-left"><i class="fa-solid fa-money-bill-trend-up fa-lg icon-market-left"></i>Стоимость инвентаря steam</a>
        </div>
        {% if user.is_authenticated %}
          <div class="market-main-left" style="margin-top: 15px; height: 465px;">
            <label class="market-link-left mll-fix">
              <div style="display: flex;">
                <div style="margin: 0 auto 0 0;">
                  <i class="fa-solid fa-sack-dollar fa-lg icon-market-left"></i>Баланс
                </div>
                <div>
                  <label style="color: #ff506f;">{{ user.balance }} <i class="fa-solid fa-ruble-sign fa-sm" style="padding-right: 3px;"></i></label>
                </div>
              </div>
            </label>
            <a href="" class="market-link-left"><i class="fa-solid fa-circle-plus fa-lg icon-market-left"></i>Пополнить баланс</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-circle-minus fa-lg icon-market-left"></i>Вывести средства</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-money-bill-transfer fa-lg icon-market-left"></i>Перевести средства</a>
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a href="{% url 'market:my_accs' %}" class="market-link-left"><i class="fa-solid fa-shop fa-lg icon-market-left"></i>Мои аккаунты</a>
            <a href="{% url 'market:my_buy_accs' %}" class="market-link-left"><i class="fa-solid fa-bag-shopping fa-lg icon-market-left"></i>Мои покупки</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-bars-staggered icon-market-left"></i>Мои операции</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-bookmark fa-lg icon-market-left"></i>Избранное</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-tag fa-lg icon-market-left"></i>Метки</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-user-xmark fa-lg icon-market-left"></i>Игнор-лист продавцов</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-comments-dollar fa-lg icon-market-left"></i>Мои денежные споры</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-retweet fa-lg icon-market-left"></i>Автоплатежи</a>
          </div>
        {% endif %}
      </div>
      <div>
        <div style="margin: 0 0 20px 20px;">
          <label style="color: #d6d6d6; font-size: 20px;">Выберите категорию</label>
          <div style="margin-top: 20px;" class="ger">
            <h2>
              <a class="a-png" href="{% url 'market:group_free' 'steam' %}">
                <img src="{% static 'images/steam.png' %}" class="market-png-cat">
              </a>
            </h2>
            <h2>
              <a class="a-png" href="{% url 'market:group_free' 'ea' %}">
                <img src="{% static 'images/ea.png' %}" class="market-png-cat">
              </a>
            </h2>
            <h2>
              <a class="a-png" href="{% url 'market:group_free' 'vk' %}">
                <img src="{% static 'images/vk.png' %}" class="market-png-cat">
              </a>
            </h2>
            <h2>
              <a class="a-png" href="{% url 'market:group_free' 'telegram' %}">
                <img src="{% static 'images/telegram.png' %}" class="market-png-cat">
              </a>
            </h2>
          </div>
        </div>
        {% if accs.count != 0 %}
          <div class="acc-frame">
            <label style="margin: 20px 0 0 20px; color: #d6d6d6; font-size: 20px;">Последние аккаунты</label>
            {% for acc in accs %}
              {% if acc.buyer == None %}
                {% if acc.author.rank != 'заблокирован' %}
                  <div class="market-accs" style="margin-top: 10px;">
                    <a style="text-decoration: none;" href="{% url 'market:acc_detail' acc.id %}">
                      <div class="text-frame">
                        <div class="text-frame-div" style="margin: 0 auto 0 0;">
                          <label class="text-frame-title">{{ acc.title }}</label><br>
                          {% if acc.group.id == 1 %}
                            <img src="{% static 'images/steam.png' %}" class="market-png">
                          {% elif acc.group.id == 2 %}
                            <img src="{% static 'images/ea.png' %}" class="market-png">
                          {% elif acc.group.id == 3 %}
                            <img src="{% static 'images/vk.png' %}" class="market-png">
                          {% elif acc.group.id == 4 %}
                            <img src="{% static 'images/telegram.png' %}" class="market-png">
                          {% endif %}
                          <label class="text-frame-username {% if acc.author.username_style != 'gray-un' %}{{ acc.author.username_style }}{% endif %}" {% if acc.author.rank == 'заблокирован' %}style="text-decoration: line-through;"{% endif %}>{{ acc.author.username }}</label>
                          <span class="pink-separator"></span>
                          <label class="text-frame-text">
                            {{ acc.pub_date|date:"d E Y / H:i" }}
                          </label>
                        </div>
                        <div class="acc-price">
                          <label>{{ acc.price }}</label> <i class="fa-solid fa-ruble-sign fa-sm" style="padding-right: 3px;"></i>
                        </div>
                      </div>
                    </a>
                  </div>
                {% endif %}
              {% endif %}
            {% endfor %}
          </div>
        {% else %}
          <div class="div-market-accs">
            <label>Пусто</label>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

speedhack/templates/market/template_groups.html
{% extends 'base.html' %}
{% load static %}
{% block title %}speedhack / маркет{% endblock %}
{% block content %}
  <div class="main">
    <div class="frames_con" style="display: block;">
      <div style="margin-bottom: 20px;">
        <label class="link-title"><a href="{% url 'market:index' %}" class="link-title-main">Маркет</a> <label style="margin: 0 5px 0 5px;">/</label> <a href="{% url 'market:group_free' group.slug %}" class="link-title-main">{{ group.title }}</a></label>
      </div>
      <div style="display: flex;">
        <div style="display: block;">
          <div class="market-sell">
            <a href="{% url 'market:acc_sell' %}" class="market-sell-button">Продать аккаунт</a>
          </div>
          <div class="market-main-left">
            <a href="https://t.me/sp1edh4ck" class="market-link-left" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-circle-question fa-lg icon-market-left"></i>Нужна помощь</a>
            <a href="{% url 'market:rules' %}" class="market-link-left"><i class="fa-solid fa-book fa-lg icon-market-left"></i>Правила и гарантии</a>
            <a href="{% url 'forum:group_filter_posts' 111 %}" class="market-link-left"><i class="fa-solid fa-sheet-plastic fa-lg icon-market-left"></i>Советы и гайды</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-gear fa-lg icon-market-left"></i>Настройки маркета</a>
            <a href="{% url 'forum:profile_upgrade' request.user %}" class="market-link-left"><i class="fa-solid fa-angles-up fa-lg icon-market-left"></i>Повышение статуса</a>
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a href="{% url 'forum:post_detail' 19 %}" class="market-link-left"><i class="fa-solid fa-newspaper fa-lg icon-market-left"></i>Изменения на сайте</a>
            <a href="{% url 'forum:group_filter_posts' 108 %}" class="market-link-left"><i class="fa-solid fa-flag fa-lg icon-market-left"></i>Сообщить о баге</a>
            <a href="{% url 'forum:group_filter_posts' 109 %}" class="market-link-left"><i class="fa-solid fa-circle-info fa-lg icon-market-left"></i>Предложить идею</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-code fa-lg icon-market-left"></i>API для разработчика</a>
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a href="" class="market-link-left"><i class="fa-solid fa-money-bill-trend-up fa-lg icon-market-left"></i>Стоимость инвентаря steam</a>
          </div>
          <div class="market-main-left" style="margin-top: 15px; height: 465px;">
            <label class="market-link-left mll-fix">
              <div style="display: flex;">
                <div style="margin: 0 auto 0 0;">
                  <i class="fa-solid fa-sack-dollar fa-lg icon-market-left"></i>Баланс
                </div>
                <div>
                  <label style="color: #ff506f;">{{ user.balance }} <i class="fa-solid fa-ruble-sign fa-sm" style="padding-right: 3px;"></i></label>
                </div>
              </div>
            </label>
            <a href="" class="market-link-left"><i class="fa-solid fa-circle-plus fa-lg icon-market-left"></i>Пополнить баланс</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-circle-minus fa-lg icon-market-left"></i>Вывести средства</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-money-bill-transfer fa-lg icon-market-left"></i>Перевести средства</a>
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a href="{% url 'market:my_accs' %}" class="market-link-left"><i class="fa-solid fa-shop fa-lg icon-market-left"></i>Мои аккаунты</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-bag-shopping fa-lg icon-market-left"></i>Мои покупки</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-bars-staggered icon-market-left"></i>Мои операции</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-bookmark fa-lg icon-market-left"></i>Избранное</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-tag fa-lg icon-market-left"></i>Метки</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-user-xmark fa-lg icon-market-left"></i>Игнор-лист продавцов</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-comments-dollar fa-lg icon-market-left"></i>Мои денежные споры</a>
            <a href="" class="market-link-left"><i class="fa-solid fa-retweet fa-lg icon-market-left"></i>Автоплатежи</a>
          </div>
        </div>
        <div>
          <div style="margin: 0 0 20px 20px;">
            <label style="color: #d6d6d6; font-size: 20px;">Выберите категорию</label>
            <div style="margin-top: 20px;" class="ger">
              <h2>
                <a class="a-png" href="{% url 'market:group_free' 'steam' %}">
                  <img src="{% static 'images/steam.png' %}" class="market-png-cat">
                </a>
              </h2>
              <h2>
                <a class="a-png" href="{% url 'market:group_free' 'ea' %}">
                  <img src="{% static 'images/ea.png' %}" class="market-png-cat">
                </a>
              </h2>
              <h2>
                <a class="a-png" href="{% url 'market:group_free' 'vk' %}">
                  <img src="{% static 'images/vk.png' %}" class="market-png-cat">
                </a>
              </h2>
              <h2>
                <a class="a-png" href="{% url 'market:group_free' 'telegram' %}">
                  <img src="{% static 'images/telegram.png' %}" class="market-png-cat">
                </a>
              </h2>
            </div>
          </div>
          {% if accs.count != 0 %}
            <div class="acc-frame">
              <label style="margin: 20px 0 0 20px; color: #d6d6d6; font-size: 20px;">Последние аккаунты</label>
              {% for acc in accs %}
                {% if acc.buyer == None %}
                  {% if acc.author.rank != 'заблокирован' %}
                    <div class="market-accs" style="margin-top: 10px;">
                      <a style="text-decoration: none;" href="{% url 'market:acc_detail' acc.id %}">
                        <div class="text-frame">
                          <div class="text-frame-div" style="margin: 0 auto 0 0;">
                            <label class="text-frame-title">{{ acc.title }}</label><br>
                            {% if acc.group.id == 1 %}
                              <img src="{% static 'images/steam.png' %}" class="market-png">
                            {% elif acc.group.id == 2 %}
                              <img src="{% static 'images/ea.png' %}" class="market-png">
                            {% elif acc.group.id == 3 %}
                              <img src="{% static 'images/vk.png' %}" class="market-png">
                            {% elif acc.group.id == 4 %}
                              <img src="{% static 'images/telegram.png' %}" class="market-png">
                            {% endif %}
                            <label class="text-frame-username {% if acc.author.username_style != 'gray-un' %}{{ acc.author.username_style }}{% endif %}" {% if acc.author.rank == 'заблокирован' %}style="text-decoration: line-through;"{% endif %}>{{ acc.author.username }}</label>
                            <span class="pink-separator"></span>
                            <label class="text-frame-text">
                              {{ acc.pub_date|date:"d E Y / H:i" }}
                            </label>
                          </div>
                          <div class="acc-price">
                            <label>{{ acc.price }}</label> <i class="fa-solid fa-ruble-sign fa-sm" style="padding-right: 3px;"></i>
                          </div>
                        </div>
                      </a>
                    </div>
                  {% endif %}
                {% endif %}
              {% endfor %}
            </div>
          {% else %}
            <label>Пусто</label>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}