speedhack/api/urls.py
from django.urls import path

from .views import GetUser, GetUsers, GetUserTgLink

urlpatterns = [
    path('get_users/', GetUsers.as_view()),
    path('get_user/<str:username>/', GetUser.as_view()),
    path('get_user_tg/<str:tg_link>/', GetUserTgLink.as_view()),
]

speedhack/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    # * ссылки на страницы
    path('', views.index, name='index'),
    # ? ----------
    # * страница, для отображения ошибки 403 (может пригодится)
    # path('ratelimited/', views.ratelimited, name='ratelimited'),
    # ? ----------
    path('forum/viewed_threads/', views.viewed_threads, name='viewed_threads'),
    path('forum/my_topics/', views.my_topics, name='my_topics'),
    path('forum/favourites/', views.favourites, name='favourites'),
    path('forum/tickets/open/', views.ticket_form, name='ticket_form'),
    path('group/<slug:slug>/', views.group_free, name='group_filter_posts'),
    path('group/<slug:slug>/create_thread/', views.create_thread, name='create_thread'),
    path('members/<str:username>/', views.profile, name='profile'),
    # ? ----------
    # TODO: сделать для пользователей с привилегиями короткие ссылки на профиль
    # path('<str:username>/', views.profile, name='profile'),
    # ? ----------
    path('members/<str:username>/symps/', views.symps_view, name='symps_view'),
    path('members/<str:username>/messages/', views.messages_view, name='messages_view'),
    path('members/<str:username>/subscriptions/', views.subscriptions_view, name='subscriptions_view'),
    path('members/<str:username>/subscribers/', views.subscribers_view, name='subscribers_view'),
    path('members/<str:username>/personal-details/', views.profile_personal_info_edit, name='profile_personal_info_edit'),
    path('members/<str:username>/contact-details/', views.profile_contact_info_edit, name='profile_contact_info_edit'),
    path('members/<str:username>/upgrade/', views.upgrade_temp, name='profile_upgrade'),
    # path('members/<str:username>/safety/', views.safety, name='profile_safety'),
    path('forum/create_post/', views.post_create, name='post_create'),
    path('forum/<int:post_id>/', views.post_detail, name='post_detail'),
    path('forum/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users-bans/', views.users_bans, name='users_bans'),
    path('admin-panel/tickets/', views.tickets, name='tickets'),
    path('admin-panel/ads/', views.ads, name='ads'),
    path('tickets/<str:username>/', views.my_tickets, name='my_tickets'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('<str:username>/complaint/', views.complaint, name='complaint'),
    path('users/', views.users, name='users'),
    path('misc/banned/', views.banned, name='banned'),
    path('misc/empty-page/', views.empty_page, name='empty_page'),
    path('misc/faq/', views.faq, name='faq'),
    path('misc/faq-q/', views.faq_q, name='faq_q'),
    path('misc/rules/', views.rules, name='rules'),
    path('misc/user-ag/', views.user_ag, name='user_ag'),
    path('misc/words/', views.words, name='words'),
    path('misc/successfully/', views.successfully, name='successfully'),
    path('misc/guarantor/', views.guarantor, name='guarantor'),
    path('misc/about/', views.about_us, name='about_us'),
    path('misc/ads/', views.advertisement, name='advertisement'),
    path('payment/safe-deal/', views.safe_deal, name='safe_deal'),
    # * ссылки на действия
    path('profile/<str:username>/deposit/<int:number>/', views.deposit, name='deposit'),
    path('profile/<str:username>/ban/', views.ban, name='ban'),
    path('profile/<str:username>/upgrade/<int:number>/', views.upgrade, name='upgrade'),
    path('profile/<str:username>/comment/<str:author>/<int:comment_id>/', views.delete_profile_comment, name='delete_profile_comment'),
    path('profile/<str:username>/follow/<int:number>/', views.profile_uf, name='profile_uf'),
    path('forum/<int:post_id>/favourites-post-save/<int:number>/', views.favourites_post_save, name='favourites_post_save'),
    path('forum/<int:post_id>/close/<int:number>/', views.post_oc, name='post_oc'),
    path('forum/<int:post_id>/symps/<str:username>/', views.symps_add, name='symps_add'),
    path('forum/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('forum/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # path('forum/<int:post_id>/symps-comment/<int:comment_id>/<str:username>/', views.symps_comment_add, name='symps_comment_add'),
    path('forum/<int:post_id>/comment/edit/', views.edit_comment, name='edit_comment'),
    path('forum/<int:post_id>/del-comment/<int:id>/', views.delete_comment, name='delete_comment'),
    path('admin-panel/user-edit/<str:username>/', views.admin_user_edit, name='admin_user_edit'),
    path('admin-panel/<str:username>/ban/', views.admin_ban, name='admin_ban'),
    path('admin-panel/ticket/<int:ticket_id>/close/<int:number>/', views.ticket_oc, name='ticket_oc'),
    path('admin-panel/ticket/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),
    path('ticket/<int:ticket_id>/comment/', views.add_answer, name='add_answer'),

    # Система личных сообщений
    # path('dialogs/', views.dialogs, name='dialogs'),
    # path('dialogs/create/(?P<user_id>\d+)/', views.create_dialog, name='create_dialog'),
    # path('dialogs/(?P<chat_id>\d+)/', views.messages, name='messages'),
]

speedhack/speedhack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('forum.urls', namespace='forum')),
    path('api/', include('api.urls')),
    path('market/', include('market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'tools.views.error404_page'

speedhack/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import (ActivationView, ChangeLoginPasswordView,
                         ChangePasswordView, CustomLoginView, SignUpView)

from . import views
from .forms import CustomUserLogin

app_name = 'users'

urlpatterns = [
    path('activation', ActivationView.as_view(), name='activation'),
    path('empty_user', ActivationView.as_view(), name='empty_user'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page='forum:index'), name='logout'),
    # * старый логин
    # ? ----------
    # path(
    #     'login/',
    #     LoginView.as_view(template_name='users/login.html',
    #                       authentication_form=CustomUserLogin),
    #     name='login'
    # ),
    # ? ----------
    path('login/', CustomLoginView.as_view(), name='login'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('safety/', ChangeLoginPasswordView.as_view(), name='profile_safety'),
    # path(
    #     'password_reset/',
    #     PasswordResetView.as_view(
    #         template_name='users/password_reset_form.html'),
    #     name='password_reset'
    # ),
    # path(
    #     'password_reset/done/',
    #     PasswordResetDoneView.as_view(
    #         template_name='users/password_reset_done.html'),
    #     name='password_reset_done'
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     PasswordResetConfirmView.as_view(
    #         template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'
    # ),
    # path(
    #     'reset/done/',
    #     PasswordResetCompleteView.as_view(
    #         template_name='password_reset_complete.html'),
    #     name='password_reset_complete'
    # ),
]

speedhack/users/forms.py
from random import randint

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.shortcuts import redirect

from users.widgets import AvatarWidget

from .models import CustomUser

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        min_length=4,
        max_length=15,
        widget=forms.TextInput(attrs={'class': 'field-input',})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'field-input',})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'field-input',})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1',)

    def save(self):
        user = super().save(commit=False)
        user.is_active = False
        # token = default_token_generator.make_token(user)
        # uid = urlsafe_base64_encode(force_bytes(user.pk))
        # activation_url = reverse_lazy('confirm_email', kwargs={'uidb64': uid, 'token': token})
        # current_site = Forum.objects.get_current().domain
        # user.activation_code = f'http://{current_site}{activation_url}'
        user.activation_code = randint(100000, 999999)
        user.save()
        return user

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['password2']
        self.fields['password1'].help_text = None
        self.fields['username'].help_text = None


class CustomUserLogin(forms.Form):
    username = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'class': 'field-input',})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'field-input',})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'password',)

    def confirm_login_allowed(self, user):
        if not user.is_active:
            return redirect('users:activation')


class CustomUserChangePassForm(forms.Form):
    username = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'class': 'field-input',})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'field-input',})
    )
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'field-input',})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'password', 'new_password',)


class CustomUserChangePassLoginForm(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'profile-edit-field profile-edit-field-height',})
    )
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'profile-edit-field profile-edit-field-height',})
    )

    class Meta:
        model = CustomUser
        fields = ('password', 'new_password',)


class CustomUserChangeForm(UserChangeForm):
    description = forms.CharField(required=False)
    occupation = forms.CharField(required=False)
    interests = forms.CharField(required=False)

    class Meta:
        widgets = {
            "avatar": AvatarWidget,
        }


class UserPersonalForm(forms.ModelForm):
    username_style = forms.CharField(required=False)
    banner = forms.CharField(required=False)
    description = forms.CharField(required=False)
    brt_day = forms.CharField(required=False)
    brt_month = forms.CharField(required=False)
    brt_year = forms.CharField(required=False, min_length=4, max_length=4)
    occupation = forms.CharField(required=False)
    interests = forms.CharField(required=False)

    class Meta:
        model = CustomUser
        fields = (
            'description',
            'avatar',
            'profile_background',
            'username_style',
            'banner',
            'gender',
            'brt_day',
            'brt_month',
            'brt_year',
            'occupation',
            'interests',
        )
        widgets = {
            "avatar": AvatarWidget,
        }


class UserContactForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            'tg_link',
            'vk_link',
            'discord_link',
            'steam_link',
            'github_link',
        )


class UserProfileAdminForm(forms.ModelForm):
    username = forms.CharField(required=False)
    rank = forms.CharField(required=False)
    rank_lvl = forms.CharField(required=False)
    privilege = forms.CharField(required=False)
    market_privilege = forms.CharField(required=False)
    time_buy_market_privilege = forms.CharField(required=False)
    buy_privilege = forms.CharField(required=False)
    time_buy_privilege = forms.CharField(required=False)
    profile_sub = forms.CharField(required=False)
    time_buy_profile_sub = forms.CharField(required=False)
    tg_link = forms.CharField(required=False)
    vk_link = forms.CharField(required=False)
    discord_link = forms.CharField(required=False)
    steam_link = forms.CharField(required=False)
    github_link = forms.CharField(required=False)
    scam = forms.CharField(required=False)
    username_style = forms.CharField(required=False)
    gender = forms.CharField(required=False)
    brt_day = forms.CharField(required=False)
    brt_month = forms.CharField(required=False)
    brt_year = forms.CharField(required=False, min_length=4, max_length=4)
    description = forms.CharField(required=False)
    occupation = forms.CharField(required=False)
    interests = forms.CharField(required=False)

    class Meta:
        model = CustomUser
        fields = (
            'username',
            'rank',
            'rank_lvl',
            'privilege',
            'buy_privilege',
            'time_buy_privilege',
            'market_privilege',
            'time_buy_market_privilege',
            'tg_link',
            'vk_link',
            'discord_link',
            'steam_link',
            'github_link',
            'description',
            'occupation',
            'interests',
            'gender',
            'brt_day',
            'brt_month',
            'brt_year',
            'username_style',
            'scam',
        )

speedhack/templates/users/activation.html
{% extends "base.html" %}
{% load static %}
{% block title %}speedhack / регистрация{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="main">
    <div class="frame-registration">
      <p style="text-align: center;"><img class="logo" src="{% static 'images/speedhack_logo.png' %}" alt="img"></p>
      <div class="preview">
        <span class="login-text">Активация почты</span>
      </div>
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <div class="form input-box">
          <input type="text" name="activation_code" placeholder="Введите код активации" class="input-ret">
        </div>
        <button type="submit" class="button-form btn-reg">Активировать</button>
      </form>
    </div>
  </div>
{% endblock %}

speedhack/templates/users/banned.html
{% extends "base.html" %}
{% block title %}speedhack / страница блокировки{% endblock %}
{% load static %}
{% block content %}
  <div class="main">
    <div class="frame-banned_con">
      <span class="logout-text" style="color: #515151; font-size: 18px; font-weight: 700;">Ваш аккаунт заблокирован, вы не можете полноценно взаимодействовать с форумом</span>
    </div>
  </div>
{% endblock %}

speedhack/templates/users/close.html
{% extends "base.html" %}
{% block title %}speedhack / страница блокировки{% endblock %}
{% load static %}
{% block content %}
  <div class="main">
    <div class="frame-banned_con">
      <span class="logout-text">Для продажи аккаунтов необходимо купить доступ к маркету.</span>
      <a class="logout-text">Приобрести доступ к маркету</a>
    </div>
  </div>
{% endblock %}

speedhack/templates/users/empty_user.html
{% extends "base.html" %}
{% block title %}speedhack / успех{% endblock %}
{% load static %}
{% block content %}
  <div class="main">
    <div class="frame-banned_con">
      <span class="logout-text" style="color: #515151; font-size: 18px; font-weight: 700;">Данной страницы не существует / error 404</span>
    </div>
  </div>
{% endblock %}

speedhack/templates/users/login.html
{% extends "base.html" %}
{% block title %}speedhack / вход{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="main">
    <div class="frame-login">
      <p style="text-align: center;"><img class="logo" src="{% static 'images/speedhack_logo.png' %}" alt="img"></p>
      <div class="preview">
        <span class="login-text">Вход на сайт</span>
      </div>
      <form method="post" {% if action_url %}action="{% url action_url %}" {% endif %} id="login_form">
        {% csrf_token %}
        {% comment %} {% for field in form %}
          <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
            {{ field|addclass:"input-ret" }}
            {% if field.label == "Username" %}
              <label for="Имя пользователя">Логин</label>
              <i class="fa-solid fa-user fa-lg icon-login"></i>
            {% elif field.label == "Password" %}
              <label>Пароль</label>
              <i class="fa-solid fa-lock fa-lg icon-login"></i>
            {% endif %}
          </div>
        {% endfor %} {% endcomment %}
        <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
          <input class="input-ret" type="text" name="username" id="id_username" autocomplete="off" style="margin-right: 5px;" placeholder="Логин...">
          <i class="fa-solid fa-user fa-lg icon-login"></i>
        </div>
        {% comment %} <div class="error"></div> {% endcomment %}
        <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
          <input class="input-ret" type="password" name="password" id="id_password" autocomplete="off" style="margin-right: 5px;" placeholder="Пароль...">
          <i class="fa-solid fa-lock fa-lg icon-login"></i>
        </div>
        {% if messages %}
          {% for message in messages %}
            <div class="login-error">{{ message }}</div>
          {% endfor %}
        {% endif %}
        {% comment %} <div class="error"></div> {% endcomment %}
        <div class="remember-me" style="justify-content: space-between;">
          <label>
            <label class="checkbox style-c" style="margin-top: -5px;">
              <input type="checkbox" style="position: static; top: 5px;">
              <div class="checkbox__checkmark"></div>
            </label>
            Запомнить меня
          </label>
          <a href="{% url 'users:password_change' %}" class="login-link-a">Забыли пароль?</a>
        </div>
        <button type="submit" id="submit_login_btn" class="button-form">Войти</button>
        <div class="login-link">
          <label>Нет аккаунта? <a href="{% url 'users:signup' %}" class="login-link-a">Зарегистрироваться</a></label>
        </div>
      </form>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/header.js' %}"></script>
{% endblock %}

speedhack/templates/users/logout.html
{% extends "base.html" %}
{% block title %}speedhack / выход{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="main">
    <div class="frame-logout_con">
      <span class="logout-text">Вы вышли из аккаунта</span>
    </div>
  </div>
{% endblock %}

speedhack/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}speedhack / смена пароля{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="main">
    <div class="frame-login">
      <p style="text-align: center;"><img class="logo" src="{% static 'images/speedhack_logo.png' %}" alt="img"></p>
      <div class="preview">
        <span class="login-text">Смена пароля</span>
      </div>
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}
      <form method="post" {% if action_url %}action="{% url action_url %}" {% endif %}>
        {% csrf_token %}
        <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
          <input class="input-ret" type="text" name="username" id="id_username" autocomplete="off" style="margin-right: 5px;" placeholder="Логин...">
          <i class="fa-solid fa-user fa-lg icon-login"></i>
        </div>
        <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
          <input class="input-ret" type="password" name="password" id="id_password" autocomplete="off" style="margin-right: 5px;" placeholder="Старый пароль...">
          <i class="fa-solid fa-lock fa-lg icon-login"></i>
        </div>
        <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
          <input class="input-ret" type="password" name="new_password" id="id_new_password" autocomplete="off" style="margin-right: 5px;" placeholder="Новый пароль...">
          <i class="fa-solid fa-lock fa-lg icon-login"></i>
        </div>
        {% if messages %}
          {% for message in messages %}
            <div class="login-error">{{ message }}</div>
          {% endfor %}
        {% endif %}
        <button type="submit" class="button-form">Сменить пароль</button>
      </form>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/header.js' %}"></script>
{% endblock %}

speedhack/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}speedhack / регистрация{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="main">
    <div class="frame-registration">
      <p style="text-align: center;"><img class="logo" src="{% static 'images/speedhack_logo.png' %}" alt="img"></p>
      <div class="preview">
        <span class="login-text">Зарегистрироваться</span>
      </div>
      {% comment %} {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div style="color: #ff506f; margin: 5px 0 0 0; font-size: 14px;">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %} {% endcomment %}
      <form method="post" action="{% url 'users:signup' %}" id="login_form">
        {% csrf_token %}
        {% comment %} {% for field in form %}
          <div class="form input-box" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
            {{ field|addclass:"input-ret" }}
            {% if field.label == "Username" %}
              <label>Логин</label>
              <i class="fa-solid fa-user fa-lg icon-login"></i>
            {% elif field.label == "Email" %}
              <label>Почта</label>
              <i class="fa-solid fa-envelope fa-lg icon-login"></i>
            {% elif field.label == "Password1" %}
              <label>Пароль</label>
              <i class="fa-solid fa-lock fa-lg icon-login"></i>
            {% endif %}
          </div>
        {% endfor %} {% endcomment %}
        <div class="form input-box" aria-required="true">
          <input class="input-ret" type="text" name="username" id="id_username" autocomplete="off" style="margin-right: 5px;" placeholder="Логин...">
          <i class="fa-solid fa-user fa-lg icon-login"></i>
        </div>
        <div class="form input-box" aria-required="true">
          <input class="input-ret" type="email" name="email" id="id_email" autocomplete="off" style="margin-right: 5px;" placeholder="Почта...">
          <i class="fa-solid fa-envelope fa-lg icon-login"></i>
        </div>
        <div class="form input-box" aria-required="true">
          <input class="input-ret" type="password" name="password1" id="id_password1" autocomplete="off" style="margin-right: 5px;" placeholder="Пароль...">
          <i class="fa-solid fa-lock fa-lg icon-login"></i>
        </div>
        {% if messages %}
          {% for message in messages %}
            <div class="login-error">{{ message }}</div>
          {% endfor %}
        {% endif %}
        <div style="display: flex; margin-bottom: 5px;">
          <label class="checkbox style-c">
            <input type="checkbox" id="politics" onclick="politics_check();">
            <div class="checkbox__checkmark"></div>
          </label>
          <label class="field-label-help">Я согласен с <a class="link-rules" href="{% url 'forum:rules' %}" target="_blank" rel="noopener noreferrer">правилами сайта</a></label>
        </div>
        <button type="submit" id="submit_login_btn" disabled="" class="button-form btn-reg">Зарегистрироваться</button>
        <div class="login-link">
          <label>Есть аккаунт? <a href="{% url 'users:login' %}" class="login-link-a">Войти</a></label>
        </div>
        <script>
          function politics_check() {
            var submit = document.getElementById('submit_login_btn')
            if (document.getElementById('politics').checked) {
              submit.disabled = '';
            } else {
              submit.disabled = 'disabled';
            }
          }
        </script>
      </form>
    </div>
  </div>
  {% comment %} <script type="text/javascript" src="{% static 'js/auth_pages.js' %}"></script> {% endcomment %}
{% endblock %}