speedhack/api/urls.py
from django.urls import path

from .views import GetUser, GetUsers, GetUserTgLink

urlpatterns = [
    path('get_users/', GetUsers.as_view()),
    path('get_user/<str:username>/', GetUser.as_view()),
    path('get_user_tg/<str:tg_link>/', GetUserTgLink.as_view()),
]

speedhack/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    # * ссылки на страницы
    path('', views.index, name='index'),
    # ? ----------
    # * страница, для отображения ошибки 403 (может пригодится)
    # path('ratelimited/', views.ratelimited, name='ratelimited'),
    # ? ----------
    path('forum/viewed_threads/', views.viewed_threads, name='viewed_threads'),
    path('forum/my_topics/', views.my_topics, name='my_topics'),
    path('forum/favourites/', views.favourites, name='favourites'),
    path('forum/tickets/open/', views.ticket_form, name='ticket_form'),
    path('group/<slug:slug>/', views.group_free, name='group_filter_posts'),
    path('group/<slug:slug>/create_thread/', views.create_thread, name='create_thread'),
    path('members/<str:username>/', views.profile, name='profile'),
    # ? ----------
    # TODO: сделать для пользователей с привилегиями короткие ссылки на профиль
    # path('<str:username>/', views.profile, name='profile'),
    # ? ----------
    path('members/<str:username>/symps/', views.symps_view, name='symps_view'),
    path('members/<str:username>/messages/', views.messages_view, name='messages_view'),
    path('members/<str:username>/subscriptions/', views.subscriptions_view, name='subscriptions_view'),
    path('members/<str:username>/subscribers/', views.subscribers_view, name='subscribers_view'),
    path('members/<str:username>/personal-details/', views.profile_personal_info_edit, name='profile_personal_info_edit'),
    path('members/<str:username>/contact-details/', views.profile_contact_info_edit, name='profile_contact_info_edit'),
    path('members/<str:username>/upgrade/', views.upgrade_temp, name='profile_upgrade'),
    # path('members/<str:username>/safety/', views.safety, name='profile_safety'),
    path('forum/create_post/', views.post_create, name='post_create'),
    path('forum/<int:post_id>/', views.post_detail, name='post_detail'),
    path('forum/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users-bans/', views.users_bans, name='users_bans'),
    path('admin-panel/tickets/', views.tickets, name='tickets'),
    path('admin-panel/ads/', views.ads, name='ads'),
    path('tickets/<str:username>/', views.my_tickets, name='my_tickets'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('<str:username>/complaint/', views.complaint, name='complaint'),
    path('users/', views.users, name='users'),
    path('misc/banned/', views.banned, name='banned'),
    path('misc/empty-page/', views.empty_page, name='empty_page'),
    path('misc/faq/', views.faq, name='faq'),
    path('misc/faq-q/', views.faq_q, name='faq_q'),
    path('misc/rules/', views.rules, name='rules'),
    path('misc/user-ag/', views.user_ag, name='user_ag'),
    path('misc/words/', views.words, name='words'),
    path('misc/successfully/', views.successfully, name='successfully'),
    path('misc/guarantor/', views.guarantor, name='guarantor'),
    path('misc/about/', views.about_us, name='about_us'),
    path('misc/ads/', views.advertisement, name='advertisement'),
    path('payment/safe-deal/', views.safe_deal, name='safe_deal'),
    # * ссылки на действия
    path('profile/<str:username>/deposit/<int:number>/', views.deposit, name='deposit'),
    path('profile/<str:username>/ban/', views.ban, name='ban'),
    path('profile/<str:username>/upgrade/<int:number>/', views.upgrade, name='upgrade'),
    path('profile/<str:username>/comment/<str:author>/<int:comment_id>/', views.delete_profile_comment, name='delete_profile_comment'),
    path('profile/<str:username>/follow/<int:number>/', views.profile_uf, name='profile_uf'),
    path('forum/<int:post_id>/favourites-post-save/<int:number>/', views.favourites_post_save, name='favourites_post_save'),
    path('forum/<int:post_id>/close/<int:number>/', views.post_oc, name='post_oc'),
    path('forum/<int:post_id>/symps/<str:username>/', views.symps_add, name='symps_add'),
    path('forum/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('forum/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # path('forum/<int:post_id>/symps-comment/<int:comment_id>/<str:username>/', views.symps_comment_add, name='symps_comment_add'),
    path('forum/<int:post_id>/comment/edit/', views.edit_comment, name='edit_comment'),
    path('forum/<int:post_id>/del-comment/<int:id>/', views.delete_comment, name='delete_comment'),
    path('admin-panel/user-edit/<str:username>/', views.admin_user_edit, name='admin_user_edit'),
    path('admin-panel/<str:username>/ban/', views.admin_ban, name='admin_ban'),
    path('admin-panel/ticket/<int:ticket_id>/close/<int:number>/', views.ticket_oc, name='ticket_oc'),
    path('admin-panel/ticket/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),
    path('ticket/<int:ticket_id>/comment/', views.add_answer, name='add_answer'),

    # Система личных сообщений
    # path('dialogs/', views.dialogs, name='dialogs'),
    # path('dialogs/create/(?P<user_id>\d+)/', views.create_dialog, name='create_dialog'),
    # path('dialogs/(?P<chat_id>\d+)/', views.messages, name='messages'),
]

speedhack/speedhack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('forum.urls', namespace='forum')),
    path('api/', include('api.urls')),
    path('market/', include('market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'tools.views.error404_page'

speedhack/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import (ActivationView, ChangeLoginPasswordView,
                         ChangePasswordView, CustomLoginView, SignUpView)

from . import views
from .forms import CustomUserLogin

app_name = 'users'

urlpatterns = [
    path('activation', ActivationView.as_view(), name='activation'),
    path('empty_user', ActivationView.as_view(), name='empty_user'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page='forum:index'), name='logout'),
    # * старый логин
    # ? ----------
    # path(
    #     'login/',
    #     LoginView.as_view(template_name='users/login.html',
    #                       authentication_form=CustomUserLogin),
    #     name='login'
    # ),
    # ? ----------
    path('login/', CustomLoginView.as_view(), name='login'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('safety/', ChangeLoginPasswordView.as_view(), name='profile_safety'),
    # path(
    #     'password_reset/',
    #     PasswordResetView.as_view(
    #         template_name='users/password_reset_form.html'),
    #     name='password_reset'
    # ),
    # path(
    #     'password_reset/done/',
    #     PasswordResetDoneView.as_view(
    #         template_name='users/password_reset_done.html'),
    #     name='password_reset_done'
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     PasswordResetConfirmView.as_view(
    #         template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'
    # ),
    # path(
    #     'reset/done/',
    #     PasswordResetCompleteView.as_view(
    #         template_name='password_reset_complete.html'),
    #     name='password_reset_complete'
    # ),
]

speedhack/forum/forms.py
from django import forms

from users.models import BannedUser, CustomUser

from .models import Ads, Comment, Forum, HelpAnswer, HelpForum, ProfileComment


class PostForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ('group', 'title', 'text', 'image', 'notification', 'hide', 'permission', 'subscribe', 'closed', 'edit', 'open_activities', 'pinned',)


class UserBanForm(forms.ModelForm):
    class Meta:
        model = BannedUser
        fields = ('user', 'admin', 'date', 'reason', 'time_value', 'time_item',)


# class ArbitrationPostForm(forms.ModelForm):
#     class Meta:
#         model = Forum
#         fields = ('defendant', 'market', 'contacts', 'amount', 'guarantor', 'transfer', 'screens', 'description',)


# class ArbitrationPostForm(forms.ModelForm):
#     class Meta:
#         model = Forum
#         fields = ('defendant', 'market', 'contacts', 'amount', 'guarantor', 'transfer', 'screens', 'description',)


# Система личных сообщений
# class MessageForm(forms.ModelForm):
#     class Meta:
#         model = Message
#         fields = ['message']
#         labels = {'message': ""}


class HelpForm(forms.ModelForm):
    category = forms.CharField(required=True)
    priority = forms.CharField(required=True)
    title = forms.CharField(required=True)
    request = forms.CharField(required=True)
    description = forms.CharField(required=True)

    class Meta:
        model = HelpForum
        fields = ('category', 'priority', 'title', 'request', 'description',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = HelpAnswer
        fields = ('text',)


class AdsForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ('title', 'post_id', 'weeks', 'author',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'image',)


class ProfileCommentForm(forms.ModelForm):
    class Meta:
        model = ProfileComment
        fields = ('text',)


class DepositForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('save_deposit',)

speedhack/users/views.py
import re
from random import randint

from django.contrib import messages
from django.contrib.auth import (authenticate, get_user_model, login,
                                 update_session_auth_hash)
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django_ratelimit.decorators import ratelimit

from users.models import CustomUser

from .forms import (CustomUserChangePassForm, CustomUserChangePassLoginForm,
                    CustomUserCreationForm, CustomUserLogin)

User = get_user_model()


class SignUpView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('forum:index')
        else:
            form = CustomUserCreationForm()
            return render(request, 'users/signup.html', {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            send_mail(
                'Подтверждение почты',
                f'Ваш код активации: {user.activation_code}',
                'speedhack_sup@mail.ru',
                [user.email],
            )
            return redirect('users:activation')
        return render(request, 'users/signup.html', {'form': form})


class ActivationView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('forum:index')
        else:
            return render(request, 'users/activation.html')

    def post(self, request):
        activation_code = request.POST['activation_code']
        user = User.objects.filter(activation_code=activation_code).first()
        if user:
            user.is_active = True
            user.activation_code = ''
            user.save()
            return redirect('users:login')
        else:
            return redirect('users:activation')


class CustomLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('forum:index')
        else:
            form = CustomUserLogin()
            return render(request, 'users/login.html', {'form': form})

    def post(self, request):
        form = CustomUserLogin(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('forum:index')
                else:
                    u = CustomUser.objects.get(username=form.cleaned_data['username'])
                    u.activation_code = randint(100000, 999999)
                    u.save()
                    send_mail(
                        'Подтверждение почты',
                        f'Ваш код активации: {u.activation_code}',
                        'speedhack_sup@mail.ru',
                        [u.email],
                    )
                    return redirect('users:activation')
            else:
                messages.error(request, "Неверное имя пользователя или пароль")
        return render(request, 'users/login.html', {'form': form})


class ChangePasswordView(View):
    def get(self, request):
        form = CustomUserChangePassForm()
        return render(request, 'users/password_change.html', {'form': form})

    def post(self, request):
        form = CustomUserChangePassForm()
        username = request.POST['username']
        password = request.POST['password']
        new_password = request.POST['new_password']
        user = User.objects.filter(username=username).first()
        if user:
            if user.is_active:
                if user.check_password(password):
                    if password == new_password:
                        messages.error(request, "Новый пароль должен отличаться от старого")
                    elif not self.is_valid_password(new_password):
                        messages.error(request, "Пароль должен содержать минимум 8 символов, включая 1 заглавную букву, 1 строчную букву и 1 цифру")
                    else:
                        user.set_password(new_password)
                        user.save()
                        user = authenticate(request, username=username, password=new_password)
                        login(request, user)
                        return redirect('forum:index')
                else:
                    messages.error(request, "Старый пароль неверный")
            else:
                messages.error(request, "Аккаунт отключён или не был подтверждён письмом на почту")
        else:
            messages.error(request, "Пользователь не найден")
        return render(request, 'users/password_change.html', {'form': form})

    def is_valid_password(self, password):
        regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d!@#$%^&*()_+={}:;,.?-]{8,}$'
        return re.match(regex, password) is not None


class ChangeLoginPasswordView(View):
    def get(self, request):
        form = CustomUserChangePassLoginForm()
        return render(request, 'forum/safety.html', {'form': form})

    def post(self, request):
        form = CustomUserChangePassLoginForm()
        password = request.POST['password']
        new_password = request.POST['new_password']
        user = User.objects.filter(username=request.user.username).first()
        if user.check_password(password):
            if password == new_password:
                messages.error(request, "Новый пароль должен отличаться от старого")
            elif not self.is_valid_password(new_password):
                messages.error(request, "Пароль должен содержать минимум 8 символов, включая 1 заглавную букву, 1 строчную букву и 1 цифру")
            else:
                user.set_password(new_password)
                user.save()
                user = authenticate(request, username=request.user.username, password=new_password)
                login(request, user)
                return redirect('forum:index')
        else:
            messages.error(request, "Старый пароль неверный")
        return render(request, 'forum/safety.html', {'form': form})

    def is_valid_password(self, password):
        regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d!@#$%^&*()_+={}:;,.?-]{8,}$'
        return re.match(regex, password) is not None

speedhack/templates/forum/ticket_form.html
{% extends 'base.html' %}
{% block title %}speedhack / тикет{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="main">
    <div class="frame_con">
      <div class="frame-users" style="display: block; padding: 20px;">
        <form method="post" action="{{ request.path }}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="ticket-div">
            <label class="ticket-label">Категория:</label>
            <div>
              <div>
                <select name="category" id="id_category" class="default-input" style="min-width: 350px; min-height: 40px;">
                  <option value="Разблокировка аккаунта" selected="">Разблокировка аккаунта</option>
                  <option value="Проблема с пополнением средств">Проблема с пополнением средств</option>
                  <option value="Проблема с выводом средств">Проблема с выводом средств</option>
                  <option value="Разблокировка с причиной 'Вбив/отмыв'">Разблокировка с причиной "Вбив/отмыв"</option>
                  <option value="Возврат средств за привилегию">Возврат средств за привилегию</option>
                  <option value="Смена почты на аккаунте">Смена почты на аккаунте</option>
                  <option value="Разблокировка с причиной 'Взломан'">Разблокировка с причиной "Взломан"</option>
                  <option value="Другое">Другое</option>
                </select>
              </div>
              <label style="color: #444444; font-size: 16px; height: 40px;">Выберите категорию, которая больше всего подходит Вашему тикету.</label>
            </div>
          </div>
          <div class="ticket-div" style="margin-bottom: 10px;">
            <label class="ticket-label">Приоритет:</label>
            <div>
              <div>
                <select name="priority" id="id_priority" class="default-input" style="min-width: 200px; min-height: 40px;">
                  <option value="Низкий" selected="">Низкий</option>
                  <option value="Средний">Средний</option>
                  <option value="Высокий">Высокий</option>
                </select>
              </div>
            </div>
          </div>
          <div class="ticket-div" style="margin-bottom: 10px;">
            <label class="ticket-label">Заголовок:</label>
            <div>
              <input type="text" name="title" id="id_title" class="default-input" style="max-width: 720px; padding-left: 7px;" placeholder="Заголовок..." maxlength="70">
            </div>
          </div>
          <div class="ticket-div">
            <label class="ticket-label">Писали ли вы человеку который вас заблокировал?:</label>
            <div>
              <div>
                <select name="request" id="id_request" class="default-input" style="min-width: 200px; min-height: 40px;">
                  <option value="Нет" selected="">Нет</option>
                  <option value="Да">Да</option>
                </select>
              </div>
              <label style="color: #444444; font-size: 16px; height: 40px;">Обязательное поле</label>
            </div>
          </div>
          <div class="ticket-div" style="margin: 0;">
            <label class="ticket-label">Описание вопроса:</label>
            <div>
              {{ form.description|addclass:"field ticket-description" }}
            </div>
          </div>
          <button type="submit" class="button-level" style="margin-left: 310px;">Создать обращение</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

speedhack/templates/forum/tickets.html
{% extends 'base.html' %}
{% block title %}speedhack / админка{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}
  <div class="main">
    <div class="frame_con">
      <div style="display: block;">
        <div class="switch-info-admin" style="max-height: 205px;">
          <a href="{% url 'forum:admin_panel' %}" class="switch-button" style="text-decoration: none; color: #d6d6d6;">Основная админ-панель</a>
          <a href="{% url 'forum:users_bans' %}" class="switch-button" style="text-decoration: none; color: #d6d6d6;">Панель блокировки</a>
          <a href="{% url 'forum:tickets' %}" class="switch-button active-tab" style="text-decoration: none; color: #d6d6d6;">Обращения</a>
          <a href="{% url 'forum:ads' %}" class="switch-button" style="text-decoration: none; color: #d6d6d6;">Реклама</a>
        </div>
        <div class="frame-left-second-users" style="max-height: 150px;">
          <span style="color: gray; font-size: 18px;">Статистика форума</span>
          <div style="display: block; height: 200px;">
            <div style="margin-top: 15px; color: gray;">
              <label>Количество тикетов:</label>
              <label style="color: #d6d6d6;">{{ tickets_count|bf_number }}</label>
            </div>
            <div style="margin-top: 3px; color: gray;">
              <label>Открытых:</label>
              <label style="color: #d6d6d6;">{{ tickets_open.count|bf_number }}</label>
            </div>
            <div style="margin-top: 3px; color: gray;">
              <label>Закрытых:</label>
              <label style="color: #d6d6d6;">{{ tickets_close.count|bf_number }}</label>
            </div>
          </div>
        </div>
      </div>
      <div style="display: block;">
        <div class="admin-frame-right">
          <a data-tab="#tickets_open" class="button-tools active-tab">Открытые тикеты</a>
          <a data-tab="#tickets_close" class="button-tools">Закрытые</a>
        </div>
        <div class="tabItem frame-users active-tab" id="tickets_open" style="max-width: 806px;{% if tickets_open_count == 0 %}max-height: 65px;{% elif tickets_open_count == 1 %}max-height: 80px;{% elif tickets_open_count == 2 %}max-height: 185px;{% elif tickets_open_count == 3 %}max-height: 290px;{% endif %}">
          {% if tickets_open.count != 0 %}
            {% for ticket in tickets_open %}
              {% if ticket.closed == False %}
                <a href="{% url 'forum:ticket' ticket.id %}">
                  <div style="display: block;">
                    <div style="display: flex; padding: 0 20px 0 20px; margin-bottom: 10px;">
                      <div style="margin: 0 10px 0px 0; height: 40px;">
                        <img style="width: 40px; border-radius: 10px;" src="{{ ticket.author.avatar.url }}">
                      </div>
                      <div style="margin: 0 auto 0 0;">
                        <a href="{% url 'forum:profile' ticket.author %}" class="admin-link">
                          <label class="users-username {% if ticket.author.username_style != 'gray-un' %}{{ ticket.author.username_style }}{% endif %}" {% if ticket.author.rank == 'заблокирован' %}style="color: #515151; text-decoration: line-through;"{% endif %}>{{ ticket.author }}</label>
                        </a>
                      </div>
                      <div class="admin-btn" style="margin-right: 5px;">
                        <a class="admin-button" href="{% url 'forum:ticket_delete' ticket.id %}">Удалить</a>
                      </div>
                      <div class="admin-btn">
                        <a class="admin-button" href="{% url 'forum:ticket_oc' ticket.id 1 %}">Закрыть</a>
                      </div>
                    </div>
                    <div class="admin-btn" style="display: flex; padding: 0 20px 0 20px;">
                      {% comment %} <label class="role-banner" style="width: 80px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; background: {% if ticket.closed == False %}green{% else %}#393939{% endif %}">{% if ticket.closed == False %}Открыт{% else %}Закрыт{% endif %}</label> {% endcomment %}
                      <label class="role-banner" style="width: 80px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; background: {% if ticket.priority == "Низкий" %}green{% elif ticket.priority == "Средний" %}#b86e00{% elif ticket.priority == "Высокий" %}#b43300;{% endif %}">{{ ticket.priority }}</label>
                      <label class="role-banner" style="width: 30px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: {% if ticket.request == "Да" %}green{% elif ticket.request == "Нет" %}#b43300;{% endif %}">{{ ticket.request }}</label>
                      <label class="role-banner" style="width: 300px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: #393939;">{{ ticket.category }}</label>
                      <label class="role-banner" style="width: auto; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: #393939;">{{ ticket.created|date:"d E Y / H:i" }}</label>
                    </div>
                  </div>
                </a>
                {% if not forloop.last %}<hr class="admin-hr">{% endif %}
              {% endif %}
            {% endfor %}
          {% else %}
            <div style="margin: 0px 0 0 20px; text-align: center;">
              <label style="color: #515151; font-size: 18px; font-weight: 700;">Нет открытых тикетов</label>
            </div>
          {% endif %}
        </div>
        <div class="tabItem frame-users" id="tickets_close" style="max-width: 806px;{% if tickets_close.count == 0 %}max-height: 65px;{% elif tickets_close.count == 1 %}max-height: 80px;{% elif tickets_close.count == 2 %}max-height: 185px;{% elif tickets_close.count == 3 %}max-height: 290px;{% endif %}">
          {% if tickets_close.count != 0 %}
            {% for ticket in tickets_close %}
              {% if ticket.closed == True %}
                <a href="{% url 'forum:ticket' ticket.id %}">
                  <div style="display: block;">
                    <div style="display: flex; padding: 0 20px 0 20px; margin-bottom: 10px;">
                      <div style="margin: 0 10px 0px 0; height: 40px;">
                        <img style="width: 40px; border-radius: 10px;" src="{{ ticket.author.avatar.url }}">
                      </div>
                      <div style="margin: 0 auto 0 0;">
                        <a href="{% url 'forum:profile' ticket.author %}" class="admin-link">
                          <label class="users-username" {% if ticket.author.rank == 'заблокирован' %}style="color: #515151; text-decoration: line-through;"{% endif %}>{{ ticket.author }}</label>
                        </a>
                      </div>
                      <div class="admin-btn" style="margin-right: 5px;">
                        <a class="admin-button" href="{% url 'forum:ticket_delete' ticket.id %}">Удалить</a>
                      </div>
                      <div class="admin-btn">
                        <a class="admin-button" href="{% url 'forum:ticket_oc' ticket.id 2 %}">Открыть</a>
                      </div>
                    </div>
                    <div class="admin-btn" style="display: flex; padding: 0 20px 0 20px;">
                      {% comment %} <label class="role-banner" style="width: 80px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; background: {% if ticket.closed == False %}green{% else %}#393939{% endif %}">{% if ticket.closed == False %}Открыт{% else %}Закрыт{% endif %}</label> {% endcomment %}
                      <label class="role-banner" style="width: 80px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; background: {% if ticket.priority == "Низкий" %}green{% elif ticket.priority == "Средний" %}#b86e00{% elif ticket.priority == "Высокий" %}#b43300;{% endif %}">{{ ticket.priority }}</label>
                      <label class="role-banner" style="width: 30px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: {% if ticket.request == "Да" %}green{% elif ticket.request == "Нет" %}#b43300;{% endif %}">{{ ticket.request }}</label>
                      <label class="role-banner" style="width: 300px; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: #393939;">{{ ticket.category }}</label>
                      <label class="role-banner" style="width: auto; height: 25px; padding: 3px 15px 3px 15px; margin: 0px; border-radius: 10px; margin-left: 10px; background: #393939;">{{ ticket.created|date:"d E Y / H:i" }}</label>
                    </div>
                  </div>
                </a>
                {% if not forloop.last %}<hr class="admin-hr">{% endif %}
              {% endif %}
            {% endfor %}
          {% else %}
            <div style="margin: 0px 0 0 20px; text-align: center;" id="tickets_close">
              <label style="color: #515151; font-size: 18px; font-weight: 700;">Нет закрытых тикетов</label>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
{% endblock %}