speedhack/api/urls.py
from django.urls import path

from .views import GetUser, GetUsers, GetUserTgLink

urlpatterns = [
    path('get_users/', GetUsers.as_view()),
    path('get_user/<str:username>/', GetUser.as_view()),
    path('get_user_tg/<str:tg_link>/', GetUserTgLink.as_view()),
]

speedhack/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    # * ссылки на страницы
    path('', views.index, name='index'),
    # ? ----------
    # * страница, для отображения ошибки 403 (может пригодится)
    # path('ratelimited/', views.ratelimited, name='ratelimited'),
    # ? ----------
    path('forum/viewed_threads/', views.viewed_threads, name='viewed_threads'),
    path('forum/my_topics/', views.my_topics, name='my_topics'),
    path('forum/favourites/', views.favourites, name='favourites'),
    path('forum/tickets/open/', views.ticket_form, name='ticket_form'),
    path('group/<slug:slug>/', views.group_free, name='group_filter_posts'),
    path('group/<slug:slug>/create_thread/', views.create_thread, name='create_thread'),
    path('members/<str:username>/', views.profile, name='profile'),
    # ? ----------
    # TODO: сделать для пользователей с привилегиями короткие ссылки на профиль
    # path('<str:username>/', views.profile, name='profile'),
    # ? ----------
    path('members/<str:username>/symps/', views.symps_view, name='symps_view'),
    path('members/<str:username>/messages/', views.messages_view, name='messages_view'),
    path('members/<str:username>/subscriptions/', views.subscriptions_view, name='subscriptions_view'),
    path('members/<str:username>/subscribers/', views.subscribers_view, name='subscribers_view'),
    path('members/<str:username>/personal-details/', views.profile_personal_info_edit, name='profile_personal_info_edit'),
    path('members/<str:username>/contact-details/', views.profile_contact_info_edit, name='profile_contact_info_edit'),
    path('members/<str:username>/upgrade/', views.upgrade_temp, name='profile_upgrade'),
    # path('members/<str:username>/safety/', views.safety, name='profile_safety'),
    path('forum/create_post/', views.post_create, name='post_create'),
    path('forum/<int:post_id>/', views.post_detail, name='post_detail'),
    path('forum/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users-bans/', views.users_bans, name='users_bans'),
    path('admin-panel/tickets/', views.tickets, name='tickets'),
    path('admin-panel/ads/', views.ads, name='ads'),
    path('tickets/<str:username>/', views.my_tickets, name='my_tickets'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('<str:username>/complaint/', views.complaint, name='complaint'),
    path('users/', views.users, name='users'),
    path('misc/banned/', views.banned, name='banned'),
    path('misc/empty-page/', views.empty_page, name='empty_page'),
    path('misc/faq/', views.faq, name='faq'),
    path('misc/faq-q/', views.faq_q, name='faq_q'),
    path('misc/rules/', views.rules, name='rules'),
    path('misc/user-ag/', views.user_ag, name='user_ag'),
    path('misc/words/', views.words, name='words'),
    path('misc/successfully/', views.successfully, name='successfully'),
    path('misc/guarantor/', views.guarantor, name='guarantor'),
    path('misc/about/', views.about_us, name='about_us'),
    path('misc/ads/', views.advertisement, name='advertisement'),
    path('payment/safe-deal/', views.safe_deal, name='safe_deal'),
    # * ссылки на действия
    path('profile/<str:username>/deposit/<int:number>/', views.deposit, name='deposit'),
    path('profile/<str:username>/ban/', views.ban, name='ban'),
    path('profile/<str:username>/upgrade/<int:number>/', views.upgrade, name='upgrade'),
    path('profile/<str:username>/comment/<str:author>/<int:comment_id>/', views.delete_profile_comment, name='delete_profile_comment'),
    path('profile/<str:username>/follow/<int:number>/', views.profile_uf, name='profile_uf'),
    path('forum/<int:post_id>/favourites-post-save/<int:number>/', views.favourites_post_save, name='favourites_post_save'),
    path('forum/<int:post_id>/close/<int:number>/', views.post_oc, name='post_oc'),
    path('forum/<int:post_id>/symps/<str:username>/', views.symps_add, name='symps_add'),
    path('forum/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('forum/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # path('forum/<int:post_id>/symps-comment/<int:comment_id>/<str:username>/', views.symps_comment_add, name='symps_comment_add'),
    path('forum/<int:post_id>/comment/edit/', views.edit_comment, name='edit_comment'),
    path('forum/<int:post_id>/del-comment/<int:id>/', views.delete_comment, name='delete_comment'),
    path('admin-panel/user-edit/<str:username>/', views.admin_user_edit, name='admin_user_edit'),
    path('admin-panel/<str:username>/ban/', views.admin_ban, name='admin_ban'),
    path('admin-panel/ticket/<int:ticket_id>/close/<int:number>/', views.ticket_oc, name='ticket_oc'),
    path('admin-panel/ticket/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),
    path('ticket/<int:ticket_id>/comment/', views.add_answer, name='add_answer'),

    # Система личных сообщений
    # path('dialogs/', views.dialogs, name='dialogs'),
    # path('dialogs/create/(?P<user_id>\d+)/', views.create_dialog, name='create_dialog'),
    # path('dialogs/(?P<chat_id>\d+)/', views.messages, name='messages'),
]

speedhack/market/urls.py
from django.urls import path

from . import views

app_name = 'market'

urlpatterns = [
    path('', views.market, name='index'),
    path('close/', views.close, name='close'),
    path('group/<slug:slug>/', views.group_free, name='group_free'),
    path('my_accs/', views.my_accs, name='my_accs'),
    path('my_buy_accs/', views.my_buy_accs, name='my_buy_accs'),
    path('<int:acc_id>/', views.acc_detail, name='acc_detail'),
    path('<int:acc_id>/buy/', views.acc_buy, name='acc_buy'),
    path('acc_sell/', views.acc_sell, name='acc_sell'),
    path('rules/', views.rules, name='rules'),
]

speedhack/speedhack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('forum.urls', namespace='forum')),
    path('api/', include('api.urls')),
    path('market/', include('market.urls', namespace='market')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'tools.views.error404_page'

speedhack/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import (ActivationView, ChangeLoginPasswordView,
                         ChangePasswordView, CustomLoginView, SignUpView)

from . import views
from .forms import CustomUserLogin

app_name = 'users'

urlpatterns = [
    path('activation', ActivationView.as_view(), name='activation'),
    path('empty_user', ActivationView.as_view(), name='empty_user'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page='forum:index'), name='logout'),
    # * старый логин
    # ? ----------
    # path(
    #     'login/',
    #     LoginView.as_view(template_name='users/login.html',
    #                       authentication_form=CustomUserLogin),
    #     name='login'
    # ),
    # ? ----------
    path('login/', CustomLoginView.as_view(), name='login'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('safety/', ChangeLoginPasswordView.as_view(), name='profile_safety'),
    # path(
    #     'password_reset/',
    #     PasswordResetView.as_view(
    #         template_name='users/password_reset_form.html'),
    #     name='password_reset'
    # ),
    # path(
    #     'password_reset/done/',
    #     PasswordResetDoneView.as_view(
    #         template_name='users/password_reset_done.html'),
    #     name='password_reset_done'
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     PasswordResetConfirmView.as_view(
    #         template_name='users/password_reset_confirm.html'),
    #     name='password_reset_confirm'
    # ),
    # path(
    #     'reset/done/',
    #     PasswordResetCompleteView.as_view(
    #         template_name='password_reset_complete.html'),
    #     name='password_reset_complete'
    # ),
]

speedhack/templates/includes/footer.html
<footer class="footer">
  <ul>
    <a href="https://t.me/sp1edh4ck_project" class="footer-link" target="_blank" rel="noopener noreferrer" style="padding-right: 10px;">Телеграм</a>
    <a href="https://vk.com/sp1edh4ck_project" class="footer-link" target="_blank" rel="noopener noreferrer">ВКонтакте</a>
  </ul>
  <hr>
  <p style="color: #d6d6d6;">&copy; 2022 - {{ year }} Company, Inc</p>
</footer>

speedhack/templates/includes/header.html
{% load static %}
{% load user_filters %}
<header class="header">
  <div class="bg-header" id="burgerMenuId">
    <div class="bg-header-con">
      <ul>
        <div class="bg-search">
          <form action="{% if request.path == '/' %}{% url 'forum:index' %}{% elif request.path == '/forum/my_topics/' %}{% url 'forum:my_topics' %}{% endif %}">
            <input class="bg-input-search" type="search" name="search" placeholder="Поиск" aria-label="Search" autocomplete="off">
          </form>
        </div>
        <div class="bg-links">
          <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-house fa-lg bg-icons"></i>
            <div class="bg-link-text">На главную</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-file-lines fa-lg bg-icons"></i>
            <div class="bg-link-text">Статьи</div>
          </a> {% endcomment %}
          {% comment %} <a class="bg-link" href="{% url "forum:market" %}">
            <i class="fa-solid fa-basket-shopping fa-lg bg-icons"></i>
            <div class="bg-link-text">Маркет</div>
          </a> {% endcomment %}
          <a class="bg-link" href="{% url "forum:guarantor" %}">
            <i class="fa-solid fa-shield fa-lg bg-icons"></i>
            <div class="bg-link-text">Гарант</div>
          </a>
        </div>
        <div class="bg-sep">
          <div class="bg-sep-text">Каналы и чаты</div>
          <div class="bg-sep-line"></div>
        </div>
        <div class="bg-links">
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">Чат</div>
          </a> {% endcomment %}
          <a class="bg-link" href="https://t.me/speedhack_project" target="_blank" rel="noopener noreferrer">
            <i class="fa-brands fa-telegram fa-lg bg-icons"></i>
            <div class="bg-link-text">Telegram канал</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-brands fa-telegram fa-lg bg-icons"></i>
            <div class="bg-link-text">sp news</div>
          </a> {% endcomment %}
          <a class="bg-link" href="https://t.me/speedhack_chat" target="_blank" rel="noopener noreferrer">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">SP TG чат</div>
          </a>
          <a class="bg-link" href="https://vk.com/speedhack_project" target="_blank" rel="noopener noreferrer">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">Группа ВКонтакте</div>
          </a>
          <a class="bg-link" href="https://discord.gg/HH8bCVsyTf" target="_blank" rel="noopener noreferrer">
            <i class="fa-solid fa-microphone fa-lg bg-icons"></i>
            <div class="bg-link-text">Discord сервер</div>
          </a>
        </div>
        <div class="bg-sep">
          <div class="bg-sep-text">Другое</div>
          <div class="bg-sep-line"></div>
        </div>
        <div class="bg-links">
          <a class="bg-link" href="{% url "forum:users" %}">
            {% comment %} <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i> {% endcomment %}
            <i class="fa-solid fa-users fa-lg bg-icons"></i>
            <div class="bg-link-text">Пользователи</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">Заблокированные</div>
          </a> {% endcomment %}
          <a class="bg-link" href="{% url "forum:rules" %}">
            <i class="fa-solid fa-triangle-exclamation fa-lg bg-icons"></i>
            <div class="bg-link-text">Правила форума</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:ticket_form" %}">
            <i class="fa-solid fa-circle-question fa-lg bg-icons"></i>
            <div class="bg-link-text">Не пришли деньги?</div>
          </a> {% endcomment %}
          <a class="bg-link" href="{% url "forum:faq" %}">
            <i class="fa-solid fa-circle-exclamation fa-lg bg-icons"></i>
            <div class="bg-link-text">FAQ</div>
          </a>
          <a class="bg-link" href="{% url "forum:advertisement" %}">
            <i class="fa-solid fa-chart-pie fa-lg bg-icons"></i>
            <div class="bg-link-text">Реклама</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">Турниры</div>
          </a> {% endcomment %}
          <a class="bg-link" href="{% url "forum:about_us" %}">
            <i class="fa-solid fa-s fa-lg bg-icons"></i>
            <div class="bg-link-text">О нас</div>
          </a>
          <a class="bg-link" href="{% url "forum:ticket_form" %}">
            <i class="fa-solid fa-circle-question fa-lg bg-icons"></i>
            <div class="bg-link-text">Нужна помощь</div>
          </a>
          {% comment %} <a class="bg-link" href="{% url "forum:index" %}">
            <i class="fa-solid fa-comment-dots fa-lg bg-icons"></i>
            <div class="bg-link-text">Switch to English</div>
          </a> {% endcomment %}
        </div>
      </ul>
    </div>
    <script type="text/javascript" src="{% static "js/misc.js" %}" defer></script>
  </div>
  <div class="header-con">
    <a href="/"><img class="brandLogo brandLogo-op" src="{% static 'images/speedhack_logo.png' %}" alt="speedhack"></a>
    <div id="burgerBtnId"><i class="fa-solid fa-bars fa-2xl burger-btn"></i></div>
    <i class="fa-solid fa-grip-lines fa-2xl icon-burger"></i>
    <div class="header-menu" id="menu">
      <ul class="menu-list menu-list-op">
        <li class="menu-item"><a href="{% url 'forum:index' %}" class="menu-link">Форум</a></li>
        {% comment %} <li class="menu-item"><a href="{% url 'market:index' %}" class="menu-link">Маркет</a></li> {% endcomment %}
        <li class="menu-item"><a href="{% url 'forum:guarantor' %}" class="menu-link">Гарант</a></li>
        <li class="menu-item">
          <div class="window-main">
            <a class="window-button">Соц. сети <i class="fas fa-angle-down fa-sm icons-header"></i></a>
            <div style="padding-top: 10px;">
              <div class="window-other">
                <a href="https://t.me/speedhack_project" target="_blank" rel="noopener noreferrer" class="window-button-second">Telegram канал</a>
                <a href="https://t.me/speedhack_chat" target="_blank" rel="noopener noreferrer" class="window-button-second">Telegram чат</a>
                <a href="https://vk.com/speedhack_project" target="_blank" rel="noopener noreferrer" class="window-button-second">Группа ВКонтакте</a>
                <a href="https://discord.gg/HH8bCVsyTf" target="_blank" rel="noopener noreferrer" class="window-button-second">Discord сервер</a>
              </div>
            </div>
          </div>
        </li>
        <li class="menu-item">
          <div class="window-main">
            <a class="window-button">Другое <i class="fa fa-angle-down fa-sm icons-header"></i></a>
            <div style="padding-top: 10px;">
              <div class="window-other">
                <a href="{% url 'forum:ticket_form' %}" class="window-button-second">Нужна помощь?</a>
                <a href="{% url 'forum:users' %}" class="window-button-second">Пользователи</a>
                <a href="{% url 'forum:faq' %}" class="window-button-second">FAQ</a>
                <a href="{% url 'forum:rules' %}" class="window-button-second">Правила форума</a>
                <a href="{% url 'forum:advertisement' %}" class="window-button-second">Реклама</a>
              </div>
            </div>
          </div>
        </li>
        {% if request.user.is_authenticated and request.user|permission_access:'designer' %}
          <li class="menu-item"><a href="{% url 'forum:admin_panel' %}" class="menu-link">Админка</a></li>
        {% endif %}
      </ul>
    </div>
    {% if request.user.is_authenticated %}
      {% comment %} <img class="notification" src="{% static 'images/notifications.png' %}"> {% endcomment %}
      <div class="window-main">
        <div class="window-button" style="display: flex;">
          <div style="margin-right: 10px;">
            <a class="{% if request.user.username_style != 'gray-un' and request.user.rank != 'заблокирован' %}{{ request.user.username_style }}{% endif %}" {% if request.user.rank == 'заблокирован' %}style="text-decoration: line-through;"{% endif %}>{{ request.user }}</a>
          </div>
          <div class="user-avatar-header-first">
            <img class="user-avatar-header" src="{{ request.user.avatar.url }}" >
          </div>
        </div>
        <div style="padding-top: 10px;">
          <div class="window-other" style="right: 0;">
            <a class="window-button-second" href="{% url 'forum:profile' user.username %}">Мой профиль</a>
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a class="window-button-second">Баланс: {{ user.balance|bf_number }} <i class="fas fa-ruble-sign fa-lg icon-rub"></i></a>
            {% comment %} <a class="window-button-second" href="{% url 'market:my_accs' %}">Мои аккаунты</a> {% endcomment %}
            {% comment %} <a class="window-button-second" href="{% url 'market:my_buy_accs' %}">Мои покупки</a> {% endcomment %}
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <a class="window-button-second" href="{% url 'forum:my_topics' %}">Мои темы</a>
            <a class="window-button-second" href="{% url 'forum:messages_view' request.user.username %}">Мои сообщения</a>
            <a class="window-button-second" href="{% url 'forum:my_tickets' request.user.username %}">Мои тикеты</a>
            <a class="window-button-second" href="{% url 'forum:favourites' %}">Избранное</a>
            <a class="window-button-second" href="{% url 'forum:profile_personal_info_edit' user.username %}">Настройки профиля</a>
            {% comment %} <a class="window-button-second" href="#">Switch to English</a> {% endcomment %}
            <hr style="margin: 5px 0px; border: 1px solid #444444;">
            <form method="post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <button class="window-button-bb" type="submit">Выйти</button>
            </form>
            {% comment %} <a class="window-button-second" href="{% url 'users:logout' %}">Выйти</a> {% endcomment %}
          </div>
        </div>
      </div>
    {% else %}
      <div>
        <a href="{% url 'users:login' %}" class="button" style="font-weight: 700;">Логин</a>
        <a href="{% url 'users:signup' %}" class="button-off" style="font-weight: 700;">Регистрация</a>
      </div>
    {% endif %}
  </div>
  <script type="text/javascript" src="{% static 'js/header.js' %}"></script>
</header>

speedhack/templates/includes/paginator.html
{% if objects.has_other_pages %}
  <nav aria-label="Page navigation" class="">
    <ul class="pagination">
      {% if objects.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
      {% endif %}
      {% for i in objects.paginator.page_range %}
        {% if objects.number == i and objects.number != 1 %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if objects.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ objects.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}